CharacterNames = ['Baby Peach', 'Baby Daisy', 'Baby Rosalina', 'Lemmy', 'Baby Mario', 'Baby Mario', 'Baby Luigi', 'Dry Bones', 'Light Mii', 'Toadette', 'Wendy', 'Isabelle', 'Koopa Troopa', 'Lakitu', 'Bowser Jr.', 'Toad', 'Shy Guy', 'Larry', 'Cat Peach', 'Inkling Girl', 'Female Villager', 'Peach', 'Daisy', 'Yoshi', 'Birdo', 'Tanooki Mario', 'Inkling Boy', 'Male Villager', 'Mario', 'Ludwig', 'Medium Mii', 'Luigi', 'Iggy', 'Rosalina', 'King Boo', 'Link', 'Metal Mario', 'Gold Mario', 'Pink Gold Peach', 'Waluigi', 'Donkey Kong', 'Roy', 'Wario', 'Dry Bowser', 'Bowser', 'Morton', 'Heavy Mii']
KartNames = ['Standard Kart', 'The Duke', '300 SL Roadster', 'Pipe Frame', 'Varmint', 'City Tripper', 'Mach 8', 'Sports Coupe', 'Inkstriker', 'Steel Driver', 'Tri-Speeder', 'Bone Rattler', 'Cat Cruiser', 'Teddy Buggy', 'Comet', 'Yoshi Bike', 'Circuit Special', 'B-Dasher', 'P-Wing', 'Badwagon', 'GLA', 'Standard ATV', 'Prancer', 'Sport Bike', 'Jet Bike', 'Biddybuggy', 'Mr Scooty',' Landship', 'Streetle', 'Sneaker', 'Gold Standard', 'Master Cycle', 'W 25 Silver Arrow', 'Standard Bike', 'Flame Rider', 'Wild Wiggler', 'Blue Falcon', 'Splat Buggy', 'Tanooki Kart', 'Koopa Clown', 'Master Cycle Zero']
WheelNames = ['Standard', 'Blue Standard', 'GLA Tires', 'Monster', 'Hot Monster', 'Ancient Tires', 'Roller', 'Azure Roller', 'Slim', 'Wood', 'Crimson Slim', 'Slick', 'Cyber Slick', 'Metal', 'Gold Tires', 'Button', 'Leaf Tires', 'Off-Road', 'Retro Off-Road', 'Triforce Tires', 'Sponge', 'Cushion']
GliderNames = ['Super Glider', 'Waddle WIng', 'Hylian Kite', 'Cloud Glider', 'Parachute', 'Flower Glider', 'Paper Glider', 'Wario Wing', 'Plane Glider', 'Gold Glider', 'Paraglider', 'Peach Parasol', 'Parafoil', 'Bowser Kite', 'MKTV Parafoil']
CharacterData = {
    'Baby Peach':{'Speed':'','MiniTurbo':'','Emojii':''},
    'Baby Daisy':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Baby Rosalina':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Lemmy':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Baby Mario':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Baby Mario':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Baby Luigi':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Dry Bones':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Light Mii':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Toadette':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Wendy':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Isabelle':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Koopa Troopa':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Lakitu':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Bowser Jr.':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Toad':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Shy Guy':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Larry':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Cat Peach':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Inkling Girl':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Female Villager':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Peach':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Daisy':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Yoshi':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Birdo':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Tanooki Mario':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Inkling Boy':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Male Villager':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Mario':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Ludwig':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Medium Mii':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Luigi':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Iggy':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Rosalina':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'King Boo':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Link':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Metal Mario':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Gold Mario':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Pink Gold Peach':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Waluigi':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Donkey Kong':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Roy':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Wario':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Dry Bowser':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Bowser':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Morton':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Heavy Mii':{'Speed':'','MiniTurbo':'','Emojii':''}
    }
KartData = {
    'Standard Kart':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'The Duke':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    '300 SL Roadster':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Pipe Frame':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Varmint':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'City Tripper':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Mach 8':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Sports Coupe':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Inkstriker':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Steel Driver':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Tri-Speeder':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Bone Rattler':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Cat Cruiser':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Teddy Buggy':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Comet':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Yoshi Bike':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Circuit Special':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'B-Dasher':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'P-Wing':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Badwagon':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'GLA':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Standard ATV':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Prancer':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Sport Bike':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Jet Bike':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Biddybuggy':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Mr Scooty':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Landship':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Streetle':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Sneaker':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Gold Standard':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Master Cycle':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'W 25 Silver Arrow':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Standard Bike':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Flame Rider':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Wild Wiggler':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Blue Falcon':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Splat Buggy':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Tanooki Kart':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Koopa Clown':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Master Cycle Zero':{'Speed':'','MiniTurbo':'','Emojii':''}
    }
WheelData = {
    'Standard':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Blue Standard':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'GLA Tires':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Monster':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Hot Monster':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Ancient Tires':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Roller':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Azure Roller':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Slim':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Wood':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Crimson Slim':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Slick':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Cyber Slick':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Metal':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Gold Tires':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Button':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Leaf Tires':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Off-Road':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Retro Off-Road':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Triforce Tires':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Sponge':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Cushion':{'Speed':'','MiniTurbo':'','Emojii':''}
    }
GliderData = {
    'Super Glider':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Waddle WIng':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Hylian Kite':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Cloud Glider':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Parachute':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Flower Glider':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Paper Glider':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Wario Wing':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Plane Glider':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Gold Glider':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Paraglider':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Peach Parasol':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Parafoil':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'Bowser Kite':{'Speed':'','MiniTurbo':'','Emojii':''}, 
    'MKTV Parafoil':{'Speed':'','MiniTurbo':'','Emojii':''}
    }
